### ISSUE TITLE
How do you choose corrector_step_size_multiplier ?

### ISSUE THREAD

**Issue by asiraudin** [andrew-cr/tauLDR#6]
Hi,

Experimenting myself with the PC scheme, I was wondering if there is any rational explanation behind the choice of the corrector_step_size_multiplier parameter ?

Do have any tips to tune it or have you simply swept over different values for each experiment ?

Best regards,

Antoine

**Comment by andrew-cr** [comment]
Hi! Unfortunately I don't have a great intuition for how to set the corrector_step_size_multiplier parameter. I would start with it at 1.0 since the step sized used for the denoising process should give a good starting point for the kind of dynamics to be expected in the corrector process but I would then just sweep the value around 1.0 in the experiments to optimize the sample quality.

**Comment by asiraudin** [comment]
Alright, thanks for the quick reply !
